language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"

install:
  - poetry install

script:
  - poetry run pytest
  - poetry run sphinx-build -b html doc doc/_build/html
  - python setup.py install # Ideally replace with poetry install
