language: python

python:
  - "3.6"
  - "3.7"
  - "3.7-dev"

install:
  - export PIPENV_IGNORE_VIRTUALENVS=1
  - pipenv install

script:
  - pipenv run test
  - pipenv run docs
  - python setup.py install
