language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"

install:
  - pip install --upgrade pip
  - pip install poetry
  - make install

script:
  - make test
  - make docs
  - make install-system
