[tool.poetry]
name = "TradingMate"
version = "2.2.0"
description = "Trading portfolio and real time stock price monitor"
authors = ["Alberto Cardellini"]
license = "MIT"
packages = [
    { include = "src" }
]
include = ["config/config.json", "data/trading_log.json"]

[tool.poetry.dependencies]
python = ">=3.6"
alpha_vantage = "^2.2.0"
yfinance = "^0.1.54"
lxml = "^4.5.1"
pygtail = "^0.11.1"

[tool.poetry.dev-dependencies]
sphinx = "^3.1.1"
sphinx-rtd-theme = "^0.5.0"
requests-mock = "^1.8.0"
docutils = "^0.16"
pytest = "^5.4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
